# Generated by Django 4.2.6 on 2023-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_currency',
            field=models.CharField(default='ILS', max_length=5),
            preserve_default=False,
        ),
    ]
