# Generated by Django 4.2.6 on 2023-12-05 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_transfer_transfer_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forex_date', models.DateField()),
                ('selling_sum', models.FloatField()),
                ('selling_currency', models.CharField(max_length=5)),
                ('rate', models.FloatField()),
                ('pursaching_sum', models.FloatField()),
                ('pursaching_currency', models.CharField(max_length=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forexes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
