# Generated by Django 4.2.6 on 2023-12-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_forex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forex',
            old_name='pursaching_currency',
            new_name='purchasing_currency',
        ),
        migrations.RenameField(
            model_name='forex',
            old_name='pursaching_sum',
            new_name='purchasing_sum',
        ),
    ]
