# Generated by Django 4.2.6 on 2023-12-07 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_pursaching_currency_forex_purchasing_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField()),
                ('stock', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sum', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
