# Generated by Django 4.2.6 on 2023-12-07 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_buy_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy_stock',
            old_name='sum',
            new_name='sum_of_stocks',
        ),
    ]
