# Generated by Django 4.2.6 on 2023-12-10 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_sum_buy_stock_sum_of_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividends_Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_date', models.DateField()),
                ('stock', models.CharField(max_length=10)),
                ('dividend_per_share', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('dividend_sum', models.FloatField()),
                ('tax', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
