# Generated by Django 4.2.6 on 2023-12-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_dividends_taxes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dividends_Taxes',
            new_name='Dividend_Tax',
        ),
    ]
