# Generated by Django 4.2.6 on 2023-12-13 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_rename_dividends_taxes_dividend_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell_Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateField()),
                ('stock', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('sum_of_stocks', models.FloatField()),
                ('tax', models.FloatField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_stocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
